package ProjectEuler

/**
  * How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
  */
object Problem29 {

  def distinctTerms(aM: Int, bM: Int): Int = {
    (2 to aM).flatMap(a => (2 to bM).map(b => math.pow(a, b))).distinct.length
  }

}
